### ISSUE TITLE
Upgrading from 2.0.15 to 2.0.16 causes the Windows Key to not be consumed when used as a modifier

### ISSUE THREAD

**Issue by markusmo3** [flyingpie/windows-terminal-quake#216]
Hey there,

i love your tool. With 2.0.15 i had some issues for a while. Mostly that it causes relayouting of spotify when i use it with that, so i thought maybe an upgrade helps. Turns out no, there are more issues than before with my workflow.

When using the tool like i have been before i encountered several issues, two of which are a dealbreaker and causes me to downgrade to 2.0.15:

- If the Windows key is used it isnt consumed by WTQ, which causes the start menu to open after the WTQ window correctly opens/closes
- The Super + Oem5 (on my keyboard that is the key below the ESC button) doesnt seem to work anymore at all. Also reconfiguring it to Super + Dead (KeyChar now, not Key) doesnt work.
- The Settings GUI hangs if i click on the "Windows" tab. The only way to get out is to restart the app completely and avoid that tab
- In the Settings UI setting a keybind sometimes does not work, especially when using the Windows key as a modifier. This again hangs the whole app and needs a full restart.
- The Spotify relayouting every time i open it with WTQ is still here, so no change on that front. Would be nice to have the option to disable any resizing and animations happening to a window though.

If you need anything, just ask me, im keen to get this fixed :)

## My System
Windows 11 Dell XPS 15

## My Settings
```json
{
	"$schema": "wtq.schema.json",
	"Apps": [
		{
			"Name": "Terminal",
			"Hotkeys": [
				{
					"Modifiers": "Super",
					"Key": "Oem5"
				}
			],
			"FileName": "wt",
			"ProcessName": "WindowsTerminal",
			"AttachMode": "FindOrStart"
		},
		{
			"Name": "Spotify",
			"Hotkeys": [
				{
					"Modifiers": "Super",
					"Key": "OemBackslash"
				}
			],
			"FileName": "spotify",
			"ProcessName": "Spotify",
			"AttachMode": "Find"
		},
		{
			"Name": "Windows Explorer",
			"Hotkeys": [
				{
					"Modifiers": "Super",
					"KeyChar": "y"
				}
			],
			"FileName": "explorer",
			"WindowClass": "CabinetWClass"
		}
	],
	"AnimationTargetFps": 60,
	"Opacity": 90,
	"HorizontalScreenCoverage": 95,
	"VerticalScreenCoverage": 95,
	"VerticalOffset": 0,
	"PreferMonitor": "Primary",
	"MonitorIndex": 0,
	"AnimationDurationMs": 100
}
```

## My Logs
Note i upgrade wtq at around 09:10

[logs-20250820.txt](https://github.com/user-attachments/files/21886383/logs-20250820.txt)

**Comment by flyingpie** [comment]
Thank you so much for your feedback, really clear and complete 🙂

Would you want to take a look how your experience is with the [prerelease of the next version](https://github.com/flyingpie/windows-terminal-quake/releases/tag/vNext)?

Multiple bugs have been fixed, including the "Windows" tab breaking everything, and changes to how keys are consumed.

Meanwhile, I'll take your settings and see if I can repro things.

**Comment by markusmo3** [comment]
Okay here is the rundown on what i did and noticed. Im a German on the QWERTZ keyboard layout btw. My system is set to english though.

- Downloaded prerelease, upacked, copied config file in without changing anything
- Shortcuts work both, but both open only Spotify, not the terminal, weirdly, and the windows key is still not consumed properly
- Changed the config to what you suggested and restarted app
- Both shortcuts dont work anymore, probably because im on the german layout, lets try with german keys

```
	"Apps": [
		{
			"Name": "Terminal",
			"Hotkeys": [{ "Modifiers": "Super", "KeyCode": "^" }],
			"FileName": "wt",
			"ProcessName": "WindowsTerminal",
			"AttachMode": "FindOrStart"
		},
		{
			"Name": "Spotify",
			"Hotkeys": [{ "Modifiers": "Super","KeyChar": "<" }],
			"FileName": "spotify",
			"ProcessName": "Spotify",
			"AttachMode": "Find"
		}
	],
```
- Spotify works, Terminal doesnt, ah there is keyCode instead keyChar, lets try that. Setting Terminals `"Hotkeys": [{ "Modifiers": "Super", "KeyChar": "^" }], `
- Spotify works, Terminal does only once, then i have to press the ^ button outside to trigger it again. I recognize this problem from my own development of global tools. This happens when the key is not consumed properly and the system is waiting for a character with diacritics, like âôî. In general, when i use that keyChar hook the key behaves very badly. To write those diacritics i had to close WTQ, otherwise when i pressed that button windows would not wait for a second char, but immediatly print "^^"


I think the most important issue is to get the keys fully consumed. That i use some weird key chars is a different topic that i could live without, even if i really dont want to.

**Comment by flyingpie** [comment]
Also, could you take a look at the logs, WTQ should show what key sequence it detects, maybe that can shed light on the issue as well?

<img width="2070" height="1519" alt="Image" src="https://github.com/user-attachments/assets/ff3b24b0-ab58-4bf5-8cc4-32fa02ecada4" />

**Comment by flyingpie** [comment]
Small correction, you need the key codes from the message "PRESSED: Got key sequence '...'" (which is still at "debug" level).

The "Vc**" keys are from the library that's sending the events, they need to be translated first.

Based on your earlier comments, I suspect you're looking for something like "Oem3" or "Oem5".

**Comment by flyingpie** [comment]
That's weird, no modifiers whatsoever 🤔 

This is the keyboard you're using, correct?

<img width="508" height="383" alt="Image" src="https://github.com/user-attachments/assets/1357a014-6c02-40b4-8639-6281fb464ee5" />

**Comment by flyingpie** [comment]
@markusmo3 So I've been spending some more time looking into how the Windows APIs work and their quirks, and I've gotten to a simpler setup, where it should be possible again to use key _chars_.

The differences with 2.0.16:
- [Pro] It no longer messes up the system keyboard layouts;
- [Pro] It doesn't mess with diacritics and dead keys;
- [Con] Shift is _not_ taken into account anymore, so when using "shift" as a modifier, one should use the base key (e.g. "1" instead of the shifted key (e.g. "!"). Since you weren't using shift, it's not particularly relevant here.

The UI is not updated yet, so I'd recommend testing with manual JSON editing for now.

So this should work with Windows Terminal (pick either option, don't have to do both):
```jsonc
{
	"$schema": "wtq.schema.json",
	"Apps": [
		{
			"Name": "Terminal",
			"Hotkeys": [
				// Using "KeyChar":
				{
					"Modifiers": "Super",
					"KeyChar": "^"
				},
				// Using "Key":
				{
					"Modifiers": "Super",
					"Key": "OemBackslash"
				}
			],
			"FileName": "wt",
			"ProcessName": "WindowsTerminal",
			"AttachMode": "FindOrStart"
		}
	]
}
```

I've put this in a separate release to hopefully avoid confusion:
https://github.com/flyingpie/windows-terminal-quake/releases/tag/vNextMoser2

Care to check a look? 🙂

**Comment by markusmo3** [comment]
Thanks so much for all the work ❤️
Yes, it is the QWERTZ layout you showed.

Using KeyChar now also works as expected and is easier to figure out than OemXYZ :)
```json
[
		{
			"Name": "Terminal",
			"Hotkeys": [
				{
					"Modifiers": "Super",
					"KeyChar": "^"
				}
			],
			"FileName": "wt",
			"ProcessName": "WindowsTerminal",
			"AttachMode": "FindOrStart"
		},
		{
			"Name": "Spotify",
			"Hotkeys": [
				{
					"Modifiers": "Super",
					"KeyChar": "<"
				}
			],
			"FileName": "spotify",
			"ProcessName": "Spotify",
			"AttachMode": "Find"
		}
	]
```

Most of the time the windows key event is also consumed, though rarely it doesn't.
Here are the logs for such a case:
```txt
09:35:32 | Debug | Wtq.Services.WtqBus | Publishing event '["Wtq.Events.WtqHotkeyPressedEvent"] "Wtq.Events.WtqHotkeyPressedEvent"'
-- | -- | -- | --
09:35:32 | Debug | Wtq.Services.SharpHook.SharpHookHotkeyService | Got app hotkey mapping for key sequence '"Modifiers:'Super' KeyChar:'<' KeyCode:'OemBackslash'"' and app '"Spotify"'
09:35:32 | Debug | Wtq.Services.SharpHook.SharpHookHotkeyService | [KeyPressed] Got key sequence '"Modifiers:'Super' KeyChar:'<' KeyCode:'OemBackslash'"'
09:35:32 | Debug | Wtq.Services.SharpHook.SharpHookHotkeyService | No hotkey mapping found for key sequence '"Modifiers:'None' KeyChar:'' KeyCode:'SuperLeft'"'
09:35:32 | Debug | Wtq.Services.SharpHook.SharpHookHotkeyService | [KeyPressed] Got key sequence '"Modifiers:'None' KeyChar:'' KeyCode:'SuperLeft'"'
```

It look like i released "Super" early, but i didn't. This happens with both hotkeys, but only when i press the shortcut quite fast. I noticed that when i do it fast it happens more like this:
```
windows pressed
< pressed [WTQ opens]
windows released [Startmenu opens]
< released
```

if i would correctly release the keys, only then the windows key is correctly consumed, and no startmenu opens, like that:
```
windows pressed
< pressed [WTQ opens]
< released
windows released
```

again, thanks!

**Comment by flyingpie** [comment]
@markusmo3 Beautiful, thank you for testing!

I've actually got to repro the windows-key-event-consume issue, and I think I understand what's going on.

Like what you already figured out, it's to do with the order of things, where we have 2 events:
- Windows key => Not suppressed
- Windows key + additional key => Suppressed

And if things are pressed and released in the right order, the first event doesn't pop the start menu.

I'll see if there's a clean way to detect this, since they're technically separate.

If I kept track correctly, this should be the state of things, correct?
- Hotkey binds not working correctly with diacritics/dead keys -> Solved
- Windows key not always suppressed, causing start menu to pop -> TODO
- Electron apps (like Spotify) becoming blank on resizes/have a "don't resize"-mode -> TODO

Also, which one of the TODO ones are most pressing for you?

**Comment by markusmo3** [comment]
Heya @flyingpie, yeah correct, like you said. I'd say the startmenu pop is more important, as that interferes more. Tracking that properly may require more detailed tracking of pressed/typed/released maybe?
